"""futures agent v1 schema

Revision ID: d5ad33d0aea4
Revises: 
Create Date: 2026-09-04 05:34:23.019792
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5ad33d0aea4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fut_data_batch',
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_fut_data_batch'))
    )
    op.create_table('fut_instrument',
    sa.Column('instrument_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id', name=op.f('pk_fut_instrument')),
    sa.UniqueConstraint('exchange', 'symbol', name='uq_fut_instrument_exchange_symbol')
    )
    op.create_table('fut_model_version',
    sa.Column('model_version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=48), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('code_commit', sa.String(length=64), nullable=True),
    sa.Column('active_from', sa.DateTime(), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('model_version_id', name=op.f('pk_fut_model_version')),
    sa.UniqueConstraint('model_type', 'version', name='uq_fut_model_version_type_version')
    )
    op.create_table('fut_contract',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('contract_code', sa.String(length=32), nullable=False),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('last_trade_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('delivery_month', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_contract_instrument_id_fut_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_fut_contract')),
    sa.UniqueConstraint('instrument_id', 'contract_code', name='uq_fut_contract_instrument_code')
    )
    with op.batch_alter_table('fut_contract', schema=None) as batch_op:
        batch_op.create_index('ix_fut_contract_code', ['contract_code'], unique=False)

    op.create_table('fut_curve_snapshot',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_curve_snapshot_instrument_id_fut_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_fut_curve_snapshot')),
    sa.UniqueConstraint('instrument_id', 'trading_date', 'source', 'revision_no', name='uq_fut_curve_snapshot_revision')
    )
    with op.batch_alter_table('fut_curve_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_fut_curve_point_in_time', ['instrument_id', 'trading_date', 'available_at'], unique=False)

    op.create_table('fut_analysis_run',
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('input_data_hash', sa.String(length=64), nullable=False),
    sa.Column('version_hash', sa.String(length=64), nullable=False),
    sa.Column('core_result_hash', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('contract_code', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('direction_score', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('direction_label', sa.String(length=32), nullable=False),
    sa.Column('opportunity_action', sa.String(length=32), nullable=False),
    sa.Column('primary_regime', sa.String(length=48), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('data_version', sa.String(length=64), nullable=False),
    sa.Column('feature_set_version', sa.String(length=64), nullable=False),
    sa.Column('factor_model_version', sa.String(length=64), nullable=False),
    sa.Column('score_config_version', sa.String(length=64), nullable=False),
    sa.Column('score_config_hash', sa.String(length=64), nullable=False),
    sa.Column('regime_rule_version', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('code_commit', sa.String(length=64), nullable=True),
    sa.Column('core_result_json', sa.JSON(), nullable=False),
    sa.Column('narrative_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_analysis_run_contract_id_fut_contract')),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_analysis_run_instrument_id_fut_instrument')),
    sa.PrimaryKeyConstraint('analysis_id', name=op.f('pk_fut_analysis_run')),
    sa.UniqueConstraint('request_hash', 'input_data_hash', 'version_hash', name='uq_fut_analysis_run_identity')
    )
    with op.batch_alter_table('fut_analysis_run', schema=None) as batch_op:
        batch_op.create_index('ix_fut_analysis_symbol_as_of', ['symbol', 'as_of'], unique=False)

    op.create_table('fut_bar_daily',
    sa.Column('bar_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('settlement_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('previous_settlement', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('turnover', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('upper_limit', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('lower_limit', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('data_batch_id', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('high_price >= low_price', name=op.f('ck_fut_bar_daily_high_ge_low')),
    sa.CheckConstraint('open_interest >= 0', name=op.f('ck_fut_bar_daily_oi_nonnegative')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_fut_bar_daily_volume_nonnegative')),
    sa.ForeignKeyConstraint(['contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_bar_daily_contract_id_fut_contract'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_batch_id'], ['fut_data_batch.batch_id'], name=op.f('fk_fut_bar_daily_data_batch_id_fut_data_batch'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('bar_id', name=op.f('pk_fut_bar_daily')),
    sa.UniqueConstraint('contract_id', 'trading_date', 'source', 'revision_no', name='uq_fut_bar_daily_revision')
    )
    with op.batch_alter_table('fut_bar_daily', schema=None) as batch_op:
        batch_op.create_index('ix_fut_bar_contract_date', ['contract_id', 'trading_date'], unique=False)
        batch_op.create_index('ix_fut_bar_point_in_time', ['contract_id', 'trading_date', 'available_at'], unique=False)

    op.create_table('fut_contract_rank_daily',
    sa.Column('rank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('volume_rank', sa.Integer(), nullable=False),
    sa.Column('open_interest_rank', sa.Integer(), nullable=False),
    sa.Column('volume_share', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('open_interest_share', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_contract_rank_daily_contract_id_fut_contract'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_contract_rank_daily_instrument_id_fut_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rank_id', name=op.f('pk_fut_contract_rank_daily')),
    sa.UniqueConstraint('instrument_id', 'contract_id', 'trading_date', 'calculation_version', name='uq_fut_contract_rank_daily')
    )
    with op.batch_alter_table('fut_contract_rank_daily', schema=None) as batch_op:
        batch_op.create_index('ix_fut_contract_rank_instrument_date', ['instrument_id', 'trading_date'], unique=False)

    op.create_table('fut_contract_spec',
    sa.Column('spec_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('margin_rate', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('trading_unit', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_contract_spec_contract_id_fut_contract'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('spec_id', name=op.f('pk_fut_contract_spec')),
    sa.UniqueConstraint('contract_id', 'effective_from', name='uq_fut_contract_spec_effective')
    )
    op.create_table('fut_curve_point',
    sa.Column('curve_point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('days_to_expiry', sa.Integer(), nullable=False),
    sa.Column('settlement_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_curve_point_contract_id_fut_contract'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['fut_curve_snapshot.snapshot_id'], name=op.f('fk_fut_curve_point_snapshot_id_fut_curve_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curve_point_id', name=op.f('pk_fut_curve_point')),
    sa.UniqueConstraint('snapshot_id', 'contract_id', name='uq_fut_curve_point_contract')
    )
    op.create_table('fut_data_quality_issue',
    sa.Column('issue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('issue_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['fut_data_batch.batch_id'], name=op.f('fk_fut_data_quality_issue_batch_id_fut_data_batch'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_data_quality_issue_contract_id_fut_contract')),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_data_quality_issue_instrument_id_fut_instrument')),
    sa.PrimaryKeyConstraint('issue_id', name=op.f('pk_fut_data_quality_issue'))
    )
    op.create_table('fut_feature_snapshot',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=False),
    sa.Column('horizon', sa.String(length=16), nullable=False),
    sa.Column('feature_set_version', sa.String(length=64), nullable=False),
    sa.Column('normalization_version', sa.String(length=64), nullable=False),
    sa.Column('input_data_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_feature_snapshot_contract_id_fut_contract')),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_feature_snapshot_instrument_id_fut_instrument')),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_fut_feature_snapshot')),
    sa.UniqueConstraint('instrument_id', 'contract_id', 'as_of', 'horizon', 'feature_set_version', 'input_data_hash', name='uq_fut_feature_snapshot_identity')
    )
    op.create_table('fut_roll_event',
    sa.Column('roll_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('from_contract_id', sa.Integer(), nullable=False),
    sa.Column('to_contract_id', sa.Integer(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('from_settlement', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('to_settlement', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('adjustment_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('roll_rule_version', sa.String(length=64), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_roll_event_from_contract_id_fut_contract')),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_roll_event_instrument_id_fut_instrument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_roll_event_to_contract_id_fut_contract')),
    sa.PrimaryKeyConstraint('roll_event_id', name=op.f('pk_fut_roll_event')),
    sa.UniqueConstraint('instrument_id', 'effective_date', 'roll_rule_version', name='uq_fut_roll_event_effective')
    )
    op.create_table('fut_analysis_audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['fut_analysis_run.analysis_id'], name=op.f('fk_fut_analysis_audit_log_analysis_id_fut_analysis_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_fut_analysis_audit_log'))
    )
    with op.batch_alter_table('fut_analysis_audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_fut_analysis_audit_analysis', ['analysis_id', 'occurred_at'], unique=False)

    op.create_table('fut_analysis_evidence',
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('factor', sa.String(length=48), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['fut_analysis_run.analysis_id'], name=op.f('fk_fut_analysis_evidence_analysis_id_fut_analysis_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'evidence_id', name=op.f('pk_fut_analysis_evidence'))
    )
    op.create_table('fut_continuous_bar_daily',
    sa.Column('continuous_bar_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('series_type', sa.String(length=32), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('source_contract_id', sa.Integer(), nullable=False),
    sa.Column('raw_settlement', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('adjusted_settlement', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('adjustment_method', sa.String(length=32), nullable=False),
    sa.Column('cumulative_adjustment', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('roll_flag', sa.Boolean(), nullable=False),
    sa.Column('roll_event_id', sa.Integer(), nullable=True),
    sa.Column('roll_rule_version', sa.String(length=64), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['fut_instrument.instrument_id'], name=op.f('fk_fut_continuous_bar_daily_instrument_id_fut_instrument'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roll_event_id'], ['fut_roll_event.roll_event_id'], name=op.f('fk_fut_continuous_bar_daily_roll_event_id_fut_roll_event')),
    sa.ForeignKeyConstraint(['source_contract_id'], ['fut_contract.contract_id'], name=op.f('fk_fut_continuous_bar_daily_source_contract_id_fut_contract')),
    sa.PrimaryKeyConstraint('continuous_bar_id', name=op.f('pk_fut_continuous_bar_daily')),
    sa.UniqueConstraint('instrument_id', 'series_type', 'trading_date', 'calculation_version', name='uq_fut_continuous_bar_daily')
    )
    with op.batch_alter_table('fut_continuous_bar_daily', schema=None) as batch_op:
        batch_op.create_index('ix_fut_continuous_instrument_date', ['instrument_id', 'trading_date'], unique=False)
        batch_op.create_index('ix_fut_continuous_point_in_time', ['instrument_id', 'trading_date', 'available_at'], unique=False)

    op.create_table('fut_factor_snapshot',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('factor_name', sa.String(length=48), nullable=False),
    sa.Column('factor_model_version', sa.String(length=64), nullable=False),
    sa.Column('score_config_version', sa.String(length=64), nullable=False),
    sa.Column('score_config_hash', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('coverage', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('contribution_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['fut_feature_snapshot.snapshot_id'], name=op.f('fk_fut_factor_snapshot_snapshot_id_fut_feature_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'factor_name', 'factor_model_version', 'score_config_version', 'score_config_hash', name=op.f('pk_fut_factor_snapshot'))
    )
    op.create_table('fut_feature_value',
    sa.Column('snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('feature_name', sa.String(length=96), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=48), nullable=True),
    sa.Column('zscore', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('percentile', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('normalized_score', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('lookback_window', sa.Integer(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['fut_feature_snapshot.snapshot_id'], name=op.f('fk_fut_feature_value_snapshot_id_fut_feature_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', 'feature_name', name=op.f('pk_fut_feature_value'))
    )
    op.create_table('fut_invalidation_rule',
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('condition_id', sa.String(length=64), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['fut_analysis_run.analysis_id'], name=op.f('fk_fut_invalidation_rule_analysis_id_fut_analysis_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id', 'condition_id', name=op.f('pk_fut_invalidation_rule'))
    )
    op.create_table('fut_invalidation_state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('condition_id', sa.String(length=64), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id', 'condition_id'], ['fut_invalidation_rule.analysis_id', 'fut_invalidation_rule.condition_id'], name='fk_fut_invalidation_state_rule', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_id', name=op.f('pk_fut_invalidation_state'))
    )
    with op.batch_alter_table('fut_invalidation_state', schema=None) as batch_op:
        batch_op.create_index('ix_fut_invalidation_state_analysis', ['analysis_id', 'evaluated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fut_invalidation_state', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_invalidation_state_analysis')

    op.drop_table('fut_invalidation_state')
    op.drop_table('fut_invalidation_rule')
    op.drop_table('fut_feature_value')
    op.drop_table('fut_factor_snapshot')
    with op.batch_alter_table('fut_continuous_bar_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_continuous_point_in_time')
        batch_op.drop_index('ix_fut_continuous_instrument_date')

    op.drop_table('fut_continuous_bar_daily')
    op.drop_table('fut_analysis_evidence')
    with op.batch_alter_table('fut_analysis_audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_analysis_audit_analysis')

    op.drop_table('fut_analysis_audit_log')
    op.drop_table('fut_roll_event')
    op.drop_table('fut_feature_snapshot')
    op.drop_table('fut_data_quality_issue')
    op.drop_table('fut_curve_point')
    op.drop_table('fut_contract_spec')
    with op.batch_alter_table('fut_contract_rank_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_contract_rank_instrument_date')

    op.drop_table('fut_contract_rank_daily')
    with op.batch_alter_table('fut_bar_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_bar_point_in_time')
        batch_op.drop_index('ix_fut_bar_contract_date')

    op.drop_table('fut_bar_daily')
    with op.batch_alter_table('fut_analysis_run', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_analysis_symbol_as_of')

    op.drop_table('fut_analysis_run')
    with op.batch_alter_table('fut_curve_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_curve_point_in_time')

    op.drop_table('fut_curve_snapshot')
    with op.batch_alter_table('fut_contract', schema=None) as batch_op:
        batch_op.drop_index('ix_fut_contract_code')

    op.drop_table('fut_contract')
    op.drop_table('fut_model_version')
    op.drop_table('fut_instrument')
    op.drop_table('fut_data_batch')
    # ### end Alembic commands ###
